### ISSUE TITLE
Add kernel stacks per TCB

### ISSUE THREAD

**Issue by DerekCresswell** [KidneyOS/KidneyOS#29]
Currently, TCBs are created with a single stack.

We will need to implement two separate stacks per TCB. A user (for the actual program being run) and a kernel stack (for syscalls and trapping). The latter can hopefully be smaller in size.

This will need to work in conjunction with both system calls and timer interrupts to ensure that our stacks are switched appropriately. It should look something like this:

```
User1 ---- trap ----> Kernel1 ---- context switch ----> Kernel2 ---- trap ----> User2 ...
```

This would mean that context switching only happens between kernel stacks and in kernel mode. Any syscall or interrupt would cause a trap frame to be placed on the current user stack and then switch into the same threads kernel stack. See [`syscall`](https://www.felixcloutier.com/x86/syscall) for some information. Some of the trap frame is placed automatically onto the stack (I believe).

**Comment by mtoohey31** [comment]
I've kinda started on this in #25, but there's still lots of work to do with it. Also one small note, it looks like `syscall` is 64-bit only, so I'm thinking we'll have to use [`int`](https://www.felixcloutier.com/x86/intn:into:int3:int1) instead. Apparently 32-bit Linux uses `int 0x80` so I've set things up the same way in #25 for now.
